In [4]:
import polars as pl
import pandas as pd 
import numpy as np
import os
import pyarrow.dataset as pads
from sklearn.metrics import mean_squared_error,root_mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import RepeatedKFold,GridSearchCV,RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
def readDataSubset(table_type, data_path = ""):
    if table_type not in ["ball-positions", "ball-events", 'player-positions', 'lineups', "game-info"]:
        print("NO")
        return -1 
    if table_type == 'lineups' or table_type == "game_info":
        return pads.dataset(source = os.path.join(os.path.dirname(__name__), data_path, table_type + '.csv'), format = 'csv')
    else:
        return pads.dataset(source = os.path.join(os.path.dirname(__name__), data_path, table_type), format = 'csv', partitioning = ['home_team', 'away_team', 'year', 'day'])

In [6]:
# Read Ball events data
ball_events_subset = readDataSubset('ball-events')
ball_events = ball_events_subset.to_table().to_pandas()
ball_events_df = pl.from_pandas(ball_events)

# Read Lineups Data
lineups_subet = readDataSubset('lineups')
lineups = lineups_subet.to_table().to_pandas()
lineups_df = pl.from_pandas(lineups)

In [7]:
ball_events_df.head(5)

shape: (5, 9)
┌────────────────┬───────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────┬──────┐
│ game_string    ┆ play_per_game ┆ timestamp ┆ player_id ┆ … ┆ home_team ┆ away_team ┆ year ┆ day  │
│ ---            ┆ ---           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---  │
│ str            ┆ f64           ┆ f64       ┆ i64       ┆   ┆ str       ┆ str       ┆ str  ┆ str  │
╞════════════════╪═══════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════╪══════╡
│ y1_d143_ADQ_AN ┆ 1.0           ┆ 50804.0   ┆ 1         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d143 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d143_ADQ_AN ┆ 1.0           ┆ 51254.0   ┆ 2         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d143 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d143_ADQ_AN ┆ 1.0           ┆ 51254.0   ┆ 0         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d143 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d143_ADQ_AN ┆ 2.0           ┆ 68204.0   ┆ 1         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d143 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d143_ADQ_AN ┆ 2.0           ┆ 68654.0   ┆ 2         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d143 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
└────────────────┴───────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────┴──────┘

In [8]:
lineups_df.head(4)

shape: (4, 21)
┌─────────────────┬────────┬─────────────┬───────────┬───┬──────────┬───────┬───────┬───────┐
│ game_string     ┆ inning ┆ half_inning ┆ home_team ┆ … ┆ batter   ┆ on_1b ┆ on_2b ┆ on_3b │
│ ---             ┆ ---    ┆ ---         ┆ ---       ┆   ┆ ---      ┆ ---   ┆ ---   ┆ ---   │
│ str             ┆ i64    ┆ str         ┆ str       ┆   ┆ str      ┆ str   ┆ str   ┆ str   │
╞═════════════════╪════════╪═════════════╪═══════════╪═══╪══════════╪═══════╪═══════╪═══════╡
│ y1_d061_VKA_PHD ┆ 1      ┆ Top         ┆ PHD       ┆ … ┆ VKA-5565 ┆ NA    ┆ NA    ┆ NA    │
│ y1_d061_VKA_PHD ┆ 1      ┆ Top         ┆ PHD       ┆ … ┆ VKA-5565 ┆ NA    ┆ NA    ┆ NA    │
│ y1_d061_VKA_PHD ┆ 1      ┆ Top         ┆ PHD       ┆ … ┆ VKA-7844 ┆ NA    ┆ NA    ┆ NA    │
│ y1_d061_VKA_PHD ┆ 1      ┆ Top         ┆ PHD       ┆ … ┆ VKA-7206 ┆ NA    ┆ NA    ┆ NA    │
└─────────────────┴────────┴─────────────┴───────────┴───┴──────────┴───────┴───────┴───────┘

## **Stolen Base Model**

- Model based on the odds of a player stealing second base when on first. 
    - features include
        - Player Speed
        - Defensive Positoning
        - Ball location
    - Output would be the should he steal or not (Red light Green Light)
        - Maybe best to use neural network, decision tree, or random forest

**First** Lets build a model only focusing on 2nd baseman positions and the odds to steal based on that. 
- lets first find where a steal happens
- Things we need
    - Player_positioning df
        - game_string
        - Play_per_game when a steal happens
        - timestamp
        - player_id
        - field_x
        - field_y
    - Lineups df
        - game_string
        - play_per_game
        - at_bat == 10
        - second_baseman == 4
        - on_1b == 11
        - on_2b == 12

- Look for squence where playy is put into play but catcher throws to 2nd base

|player_id|event_code|
|-----|-----|
|1 (Pitcher)|1 (pitch)|
|2 (Catcher)|2 (ball acquired)|
|2 (Cather) |3 (Throw)|
|4 (Second BM)| 2 (ball acquired)

In [9]:
# Collect all ball_events where a cather throws the ball
ball_events_ct = ball_events_df.sort(
    ['game_string', 'play_per_game', 'timestamp']
).filter(
    (pl.col("player_id") == 1) &
    (pl.col("ball_eventcode") == 1) &
    (pl.col("player_id").shift(-1) == 2) &
    (pl.col("ball_eventcode").shift(-1) == 2) &
    (pl.col("player_id").shift(-2) == 2) &
    (pl.col("ball_eventcode").shift(-2) == 3)# &
    #(pl.col("player_id").shift(-3) == 4) &
    #(pl.col("ball_eventcode").shift(-3) == 2)
    .over(["game_string", "play_per_game"])
).select(
    ["game_string", "play_per_game", pl.col("timestamp").alias("throw_timestamp")]
)

# Collect all 2nd BM catches with catcher throws before
ball_events_2bm = ball_events_df.sort(
    ['game_string', 'play_per_game', 'timestamp']
).filter(
    (pl.col("player_id").shift(1) == 2) &
    (pl.col("ball_eventcode").shift(1) == 3) #&
   # (pl.col("player_id") == 4) & 
   # (pl.col("ball_eventcode") == 2)
    .over(["game_string", "play_per_game"])
).select(
    ["game_string", "play_per_game", pl.col("timestamp").alias("catch_timestamp")]
)

In [10]:
ball_events_ct.drop_nulls()

shape: (352, 3)
┌─────────────────┬───────────────┬─────────────────┐
│ game_string     ┆ play_per_game ┆ throw_timestamp │
│ ---             ┆ ---           ┆ ---             │
│ str             ┆ f64           ┆ f64             │
╞═════════════════╪═══════════════╪═════════════════╡
│ y1_d061_VKA_PHD ┆ 106.0         ┆ 3.377014e6      │
│ y1_d061_VKA_PHD ┆ 208.0         ┆ 6.851814e6      │
│ y1_d061_VKA_PHD ┆ 213.0         ┆ 7.066614e6      │
│ y1_d064_VKA_PHD ┆ 80.0          ┆ 2.379142e6      │
│ y1_d064_VKA_PHD ┆ 177.0         ┆ 5.5483e6        │
│ …               ┆ …             ┆ …               │
│ y1_d212_PWH_ARN ┆ 201.0         ┆ 6.578189e6      │
│ y1_d212_QHX_ANI ┆ 189.0         ┆ 6.231921e6      │
│ y1_d213_HNO_ARN ┆ 69.0          ┆ 2.438464e6      │
│ y1_d213_HNO_ARN ┆ 315.0         ┆ 1.1541853e7     │
│ y1_d214_ARN_VAS ┆ 138.0         ┆ 4.553502e6      │
└─────────────────┴───────────────┴─────────────────┘

In [11]:
ball_events_ct.shape

(357, 3)

In [12]:
ball_events_ct.head()

shape: (5, 3)
┌─────────────┬───────────────┬─────────────────┐
│ game_string ┆ play_per_game ┆ throw_timestamp │
│ ---         ┆ ---           ┆ ---             │
│ str         ┆ f64           ┆ f64             │
╞═════════════╪═══════════════╪═════════════════╡
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
└─────────────┴───────────────┴─────────────────┘

In [13]:
ball_events_2bm.shape

(512, 3)

In [14]:
ball_events_2bm.head()

shape: (5, 3)
┌─────────────┬───────────────┬─────────────────┐
│ game_string ┆ play_per_game ┆ catch_timestamp │
│ ---         ┆ ---           ┆ ---             │
│ str         ┆ f64           ┆ f64             │
╞═════════════╪═══════════════╪═════════════════╡
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
│ NA          ┆ null          ┆ null            │
└─────────────┴───────────────┴─────────────────┘

In [15]:
# Join df together
steals_df = pl.concat([ball_events_ct, ball_events_2bm], how = "diagonal").group_by(
    ["game_string", "play_per_game"]
).agg(
    # Condonse back into 1 row per game
    pl.col("throw_timestamp").min(),
    pl.col("catch_timestamp").min()
).with_columns(
    # calcualte throw time
    throw_time = ((pl.col("catch_timestamp") - pl.col("throw_timestamp")) / 1000).round(2),
    play_per_game = pl.col("play_per_game").cast(pl.Int64)
).sort(
    # Arraneg by game_string and play_per_game
    ["game_string", "play_per_game"]
)

In [16]:
steals_df.shape

(499, 5)

In [17]:
steals_df.head()

shape: (5, 5)
┌─────────────────┬───────────────┬─────────────────┬─────────────────┬────────────┐
│ game_string     ┆ play_per_game ┆ throw_timestamp ┆ catch_timestamp ┆ throw_time │
│ ---             ┆ ---           ┆ ---             ┆ ---             ┆ ---        │
│ str             ┆ i64           ┆ f64             ┆ f64             ┆ f64        │
╞═════════════════╪═══════════════╪═════════════════╪═════════════════╪════════════╡
│ NA              ┆ null          ┆ null            ┆ null            ┆ null       │
│ y1_d061_VKA_PHD ┆ 106           ┆ 3.377014e6      ┆ 3.379364e6      ┆ 2.35       │
│ y1_d061_VKA_PHD ┆ 208           ┆ 6.851814e6      ┆ 6.854164e6      ┆ 2.35       │
│ y1_d061_VKA_PHD ┆ 213           ┆ 7.066614e6      ┆ 7.069014e6      ┆ 2.4        │
│ y1_d062_VKA_PHD ┆ 191           ┆ null            ┆ 5.605734e6      ┆ null       │
└─────────────────┴───────────────┴─────────────────┴─────────────────┴────────────┘

In [18]:
steals_df.drop_nulls()

shape: (351, 5)
┌─────────────────┬───────────────┬─────────────────┬─────────────────┬────────────┐
│ game_string     ┆ play_per_game ┆ throw_timestamp ┆ catch_timestamp ┆ throw_time │
│ ---             ┆ ---           ┆ ---             ┆ ---             ┆ ---        │
│ str             ┆ i64           ┆ f64             ┆ f64             ┆ f64        │
╞═════════════════╪═══════════════╪═════════════════╪═════════════════╪════════════╡
│ y1_d061_VKA_PHD ┆ 106           ┆ 3.377014e6      ┆ 3.379364e6      ┆ 2.35       │
│ y1_d061_VKA_PHD ┆ 208           ┆ 6.851814e6      ┆ 6.854164e6      ┆ 2.35       │
│ y1_d061_VKA_PHD ┆ 213           ┆ 7.066614e6      ┆ 7.069014e6      ┆ 2.4        │
│ y1_d064_VKA_PHD ┆ 80            ┆ 2.379142e6      ┆ 2.381419e6      ┆ 2.28       │
│ y1_d064_VKA_PHD ┆ 177           ┆ 5.5483e6        ┆ 5.550874e6      ┆ 2.57       │
│ …               ┆ …             ┆ …               ┆ …               ┆ …          │
│ y1_d212_PWH_ARN ┆ 201           ┆ 6.578189e6      ┆ 6.582314e6      ┆ 4.12       │
│ y1_d212_QHX_ANI ┆ 189           ┆ 6.231921e6      ┆ 6.234396e6      ┆ 2.48       │
│ y1_d213_HNO_ARN ┆ 69            ┆ 2.438464e6      ┆ 2.440906e6      ┆ 2.44       │
│ y1_d213_HNO_ARN ┆ 315           ┆ 1.1541853e7     ┆ 1.1546341e7     ┆ 4.49       │
│ y1_d214_ARN_VAS ┆ 138           ┆ 4.553502e6      ┆ 4.555852e6      ┆ 2.35       │
└─────────────────┴───────────────┴─────────────────┴─────────────────┴────────────┘

## 2nd Base Man Location

In [19]:
# Make vectors for game_string and play_per_game in throw times
relevant_game_string = steals_df["game_string"]
relevant_ppg = steals_df["play_per_game"]

# read in the player_pos data and filter selected game
player_pos_subset = readDataSubset("player-positions")
player_positions = player_pos_subset.to_table(filter = ((pads.field("game_string").isin(relevant_game_string)) &
                                                        (pads.field("play_per_game").isin(relevant_ppg)) & 
                                                        (pads.field("player_id") == 4))).to_pandas()
player_positions_df = pl.from_pandas(player_positions)

In [20]:
player_positions_df = player_positions_df.with_columns(play_per_game = pl.col("play_per_game").cast(pl.Int64))

In [21]:
player_positions_df.head()

shape: (5, 10)
┌────────────────┬───────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────┬──────┐
│ game_string    ┆ play_per_game ┆ timestamp ┆ player_id ┆ … ┆ home_team ┆ away_team ┆ year ┆ day  │
│ ---            ┆ ---           ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---  ┆ ---  │
│ str            ┆ i64           ┆ f64       ┆ i64       ┆   ┆ str       ┆ str       ┆ str  ┆ str  │
╞════════════════╪═══════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════╪══════╡
│ y1_d144_ADQ_AN ┆ 2             ┆ 77788.0   ┆ 4         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d144 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d144_ADQ_AN ┆ 2             ┆ 77838.0   ┆ 4         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d144 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d144_ADQ_AN ┆ 2             ┆ 77888.0   ┆ 4         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d144 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d144_ADQ_AN ┆ 2             ┆ 77938.0   ┆ 4         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d144 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
│ y1_d144_ADQ_AN ┆ 2             ┆ 77988.0   ┆ 4         ┆ … ┆ ANI       ┆ ADQ       ┆ y1   ┆ d144 │
│ I              ┆               ┆           ┆           ┆   ┆           ┆           ┆      ┆      │
└────────────────┴───────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────┴──────┘

In [22]:
player_positions_df.shape

(4974071, 10)

In [23]:
steals_positions = steals_df.join(
    player_positions_df, on = ["game_string", "play_per_game"], how = "left"
).select(
    "game_string", "play_per_game", pl.col("field_x").alias("2nd_baseman_field_x"), pl.col("field_y").alias("2nd_baseman_field_y"), "timestamp", "throw_time"
).sort(
    ["game_string", "play_per_game", "timestamp"]).unique(["play_per_game"])

In [24]:
steals_positions.head(5)

shape: (5, 6)
┌──────────────────┬───────────────┬──────────────────┬──────────────────┬────────────┬────────────┐
│ game_string      ┆ play_per_game ┆ 2nd_baseman_fiel ┆ 2nd_baseman_fiel ┆ timestamp  ┆ throw_time │
│ ---              ┆ ---           ┆ d_x              ┆ d_y              ┆ ---        ┆ ---        │
│ str              ┆ i64           ┆ ---              ┆ ---              ┆ f64        ┆ f64        │
│                  ┆               ┆ f64              ┆ f64              ┆            ┆            │
╞══════════════════╪═══════════════╪══════════════════╪══════════════════╪════════════╪════════════╡
│ y1_d159_KZR_VAS  ┆ 3             ┆ -19.5381         ┆ 152.1735         ┆ 121873.0   ┆ null       │
│ y1_d067.5_NLG_AN ┆ 134           ┆ 26.6193          ┆ 147.5385         ┆ 4.359131e6 ┆ 3.25       │
│ I                ┆               ┆                  ┆                  ┆            ┆            │
│ y1_d153.5_RME_AR ┆ 137           ┆ 24.1683          ┆ 149.2284         ┆ 4.261787e6 ┆ 2.4        │
│ N                ┆               ┆                  ┆                  ┆            ┆            │
│ y1_d094_WLI_ARN  ┆ 268           ┆ -16.4889         ┆ 143.8389         ┆ 9.147311e6 ┆ 2.35       │
│ y1_d137_EXB_ARN  ┆ 265           ┆ 50.751           ┆ 143.9901         ┆ 9.402468e6 ┆ 3.05       │
└──────────────────┴───────────────┴──────────────────┴──────────────────┴────────────┴────────────┘

In [25]:
steals_positions.shape

(259, 6)

In [26]:
# FInd the names of second baseman, batter, and runners
postions_names = lineups_df.sort(
    ["game_string", "play_per_game"]
).with_columns(
    pl.col("on_1b").shift(-1).alias("next_on_1b"),
    pl.col("on_2b").shift(-1).alias("next_on_2b"),
    pl.col("at_bat").shift(-1).alias("next_at_bat"),
    pl.col("play_per_game").shift(-1).alias("next_play"),
    play_per_game = pl.col("play_per_game").cast(pl.Int64),
).select(
    ["game_string", "play_per_game", "next_play" , "second_baseman", "at_bat", "next_at_bat", "on_1b", "next_on_1b", "on_2b", "next_on_2b"]
).unique()

In [27]:
postions_names.head(4)

shape: (4, 10)
┌────────────┬────────────┬───────────┬────────────┬───┬──────────┬────────────┬───────┬───────────┐
│ game_strin ┆ play_per_g ┆ next_play ┆ second_bas ┆ … ┆ on_1b    ┆ next_on_1b ┆ on_2b ┆ next_on_2 │
│ g          ┆ ame        ┆ ---       ┆ eman       ┆   ┆ ---      ┆ ---        ┆ ---   ┆ b         │
│ ---        ┆ ---        ┆ i64       ┆ ---        ┆   ┆ str      ┆ str        ┆ str   ┆ ---       │
│ str        ┆ i64        ┆           ┆ str        ┆   ┆          ┆            ┆       ┆ str       │
╞════════════╪════════════╪═══════════╪════════════╪═══╪══════════╪════════════╪═══════╪═══════════╡
│ y1_d149_VN ┆ 240        ┆ 241       ┆ VAS-1773   ┆ … ┆ NA       ┆ NA         ┆ NA    ┆ NA        │
│ G_VAS      ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
│ y1_d110_TH ┆ 310        ┆ 311       ┆ THF-7863   ┆ … ┆ NA       ┆ NA         ┆ NA    ┆ NA        │
│ F_ARN      ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
│ y1_d180_YX ┆ 222        ┆ 223       ┆ YXL-1727   ┆ … ┆ PHD-8619 ┆ PHD-8619   ┆ NA    ┆ NA        │
│ L_PHD      ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
│ y1_d143_KV ┆ 136        ┆ 137       ┆ VAS-1773   ┆ … ┆ KVN-0052 ┆ KVN-0052   ┆ NA    ┆ NA        │
│ N_VAS      ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
└────────────┴────────────┴───────────┴────────────┴───┴──────────┴────────────┴───────┴───────────┘

In [28]:
postions_names.shape

(76455, 10)

 Find all plays where a steal happened
lineups_2nd_steal = postions_names.sort(
    ['game_string', 'play_per_game']
).with_columns(
    pl.col("on_2b").shift(-1).alias("next_on_2b"),
    pl.col("at_bat").shift(-1).alias("next_at_bat"),
    pl.col("play_per_game").shift(-1).alias("next_play"),
    pl.col("play_per_game").shift(1).alias("before_play"),
    pl.lit(True).alias("steal_successful")
).filter(
    (pl.col("on_1b") != "NA") &
    (pl.col("on_1b") == pl.col("next_on_2b")) &
    (pl.col("at_bat") == pl.col("next_at_bat"))
).select(
   ["game_string", "before_play", "play_per_game", pl.col("play_per_game").alias("steal_play"), "next_play", "second_baseman", "at_bat", "next_at_bat", "on_1b", "on_2b", "next_on_2b", "steal_successful"]
)

lineups_2nd_steal.shape

# Find all plays where a steal failed
lineups_2nd_fails = postions_names.sort(
    ["game_string", "play_per_game"]
).with_columns(
    pl.col("on_1b").shift(-1).alias("next_on_1b"),
    pl.col("on_2b").shift(-1).alias("next_on_2b"),
    pl.col("at_bat").shift(-1).alias("next_at_bat"),
    #pl.col("play_per_game").shift(-1).alias("next_play"),
    #pl.col("play_per_game").shift(1).alias("before_play"),
    #pl.col("inning").shift(-1).alias("next_inning"),
    #pl.col("half_inning").shift(-1).alias("next_hafe"),
    pl.lit(False).alias("steal_successful")
).filter(
    (pl.col("on_1b") != "NA") &
    (pl.col("next_on_1b") == "NA") &
    (pl.col("next_on_2b") == "NA") &
    #(pl.col("inning") == pl.col("next_inning")) &
    #(pl.col("half_inning") == pl.col("next_hafe")) &
    (pl.col("at_bat") == pl.col("next_at_bat"))
).select(
   ["game_string", "play_per_game", "second_baseman", "at_bat", "next_at_bat", "on_1b", "next_on_1b", "steal_successful"]
)

In [29]:
joined_df = steals_positions.join(postions_names, on = ["game_string", "play_per_game"], how = "left").select(
    ["game_string", "play_per_game", "next_play" , "throw_time", "2nd_baseman_field_x", "2nd_baseman_field_y", "at_bat", "next_at_bat", "second_baseman", "on_1b", "next_on_1b", "on_2b", "next_on_2b"]
)

In [30]:
joined_df.shape

(263, 13)

In [31]:
joined_df.head(5)

shape: (5, 13)
┌────────────┬────────────┬───────────┬────────────┬───┬──────────┬────────────┬───────┬───────────┐
│ game_strin ┆ play_per_g ┆ next_play ┆ throw_time ┆ … ┆ on_1b    ┆ next_on_1b ┆ on_2b ┆ next_on_2 │
│ g          ┆ ame        ┆ ---       ┆ ---        ┆   ┆ ---      ┆ ---        ┆ ---   ┆ b         │
│ ---        ┆ ---        ┆ i64       ┆ f64        ┆   ┆ str      ┆ str        ┆ str   ┆ ---       │
│ str        ┆ i64        ┆           ┆            ┆   ┆          ┆            ┆       ┆ str       │
╞════════════╪════════════╪═══════════╪════════════╪═══╪══════════╪════════════╪═══════╪═══════════╡
│ y1_d159_KZ ┆ 3          ┆ 4         ┆ null       ┆ … ┆ NA       ┆ NA         ┆ NA    ┆ NA        │
│ R_VAS      ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
│ y1_d067.5_ ┆ 134        ┆ 135       ┆ 3.25       ┆ … ┆ ANI-7878 ┆ NA         ┆ NA    ┆ ANI-7878  │
│ NLG_ANI    ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
│ y1_d153.5_ ┆ 137        ┆ 138       ┆ 2.4        ┆ … ┆ RME-4608 ┆ NA         ┆ NA    ┆ RME-4608  │
│ RME_ARN    ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
│ y1_d094_WL ┆ 268        ┆ 269       ┆ 2.35       ┆ … ┆ ARN-9073 ┆ NA         ┆ NA    ┆ NA        │
│ I_ARN      ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
│ y1_d137_EX ┆ 265        ┆ 266       ┆ 3.05       ┆ … ┆ ARN-8132 ┆ NA         ┆ NA    ┆ ARN-8132  │
│ B_ARN      ┆            ┆           ┆            ┆   ┆          ┆            ┆       ┆           │
└────────────┴────────────┴───────────┴────────────┴───┴──────────┴────────────┴───────┴───────────┘

In [32]:
successful_steal = joined_df.filter(
        (pl.col("on_1b") != "NA") &
        (pl.col("on_1b") == pl.col("next_on_2b")) &
        (pl.col("at_bat") == pl.col("next_at_bat")) &
        (pl.col("on_2b") == "NA")
    ).with_columns(
        (pl.lit(True).alias("steal_successful"))
    )

In [33]:
successful_steal.shape

(47, 14)

In [34]:
successful_steal.head()

shape: (5, 14)
┌────────────┬────────────┬───────────┬────────────┬───┬───────────┬───────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ next_play ┆ throw_time ┆ … ┆ next_on_1 ┆ on_2b ┆ next_on_2 ┆ steal_suc │
│ g          ┆ ame        ┆ ---       ┆ ---        ┆   ┆ b         ┆ ---   ┆ b         ┆ cessful   │
│ ---        ┆ ---        ┆ i64       ┆ f64        ┆   ┆ ---       ┆ str   ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆           ┆            ┆   ┆ str       ┆       ┆ str       ┆ bool      │
╞════════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪═══════╪═══════════╪═══════════╡
│ y1_d067.5_ ┆ 134        ┆ 135       ┆ 3.25       ┆ … ┆ NA        ┆ NA    ┆ ANI-7878  ┆ true      │
│ NLG_ANI    ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d153.5_ ┆ 137        ┆ 138       ┆ 2.4        ┆ … ┆ NA        ┆ NA    ┆ RME-4608  ┆ true      │
│ RME_ARN    ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d137_EX ┆ 265        ┆ 266       ┆ 3.05       ┆ … ┆ NA        ┆ NA    ┆ ARN-8132  ┆ true      │
│ B_ARN      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d209_QH ┆ 399        ┆ 400       ┆ null       ┆ … ┆ NA        ┆ NA    ┆ ANI-1431  ┆ true      │
│ X_ANI      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d115_JP ┆ 6          ┆ 7         ┆ 2.34       ┆ … ┆ NA        ┆ NA    ┆ JPB-2826  ┆ true      │
│ B_ANI      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
└────────────┴────────────┴───────────┴────────────┴───┴───────────┴───────┴───────────┴───────────┘

In [35]:
failed_steal = joined_df.filter(
        (pl.col("on_1b") != "NA") &
        (pl.col("on_1b") != pl.col("next_on_2b")) &
        (pl.col("at_bat") == pl.col("next_at_bat")) &
        (pl.col("on_2b") == "NA")
    ).with_columns(
        (pl.lit(False).alias("steal_successful"))
    )

In [36]:
failed_steal.shape

(69, 14)

In [37]:
failed_steal.head()

shape: (5, 14)
┌────────────┬────────────┬───────────┬────────────┬───┬───────────┬───────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ next_play ┆ throw_time ┆ … ┆ next_on_1 ┆ on_2b ┆ next_on_2 ┆ steal_suc │
│ g          ┆ ame        ┆ ---       ┆ ---        ┆   ┆ b         ┆ ---   ┆ b         ┆ cessful   │
│ ---        ┆ ---        ┆ i64       ┆ f64        ┆   ┆ ---       ┆ str   ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆           ┆            ┆   ┆ str       ┆       ┆ str       ┆ bool      │
╞════════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪═══════╪═══════════╪═══════════╡
│ y1_d105_MS ┆ 9          ┆ 10        ┆ 2.2        ┆ … ┆ MSN-2989  ┆ NA    ┆ NA        ┆ false     │
│ N_VAS      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d140_QB ┆ 15         ┆ 16        ┆ 2.5        ┆ … ┆ QBR-7562  ┆ NA    ┆ NA        ┆ false     │
│ R_ANI      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d152_VA ┆ 286        ┆ 287       ┆ 2.55       ┆ … ┆ VAS-1238  ┆ NA    ┆ NA        ┆ false     │
│ S_PHD      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d095_NF ┆ 155        ┆ 156       ┆ 3.2        ┆ … ┆ PHD-9663  ┆ NA    ┆ NA        ┆ false     │
│ P_PHD      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
│ y1_d075_XP ┆ 158        ┆ 159       ┆ 2.51       ┆ … ┆ PHD-8619  ┆ NA    ┆ NA        ┆ false     │
│ O_PHD      ┆            ┆           ┆            ┆   ┆           ┆       ┆           ┆           │
└────────────┴────────────┴───────────┴────────────┴───┴───────────┴───────┴───────────┴───────────┘

In [38]:
final_df = pl.concat([successful_steal, failed_steal], how = "vertical"
).sort(["game_string", "play_per_game"])

In [39]:
final_df = final_df.with_columns(
    pl.when(pl.col("throw_time").is_null()).then(pl.lit(1)).otherwise(pl.lit(0)).alias("throw_results")
)

In [40]:
final_df.sample(n = 10)

shape: (10, 15)
┌────────────┬────────────┬───────────┬────────────┬───┬───────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ next_play ┆ throw_time ┆ … ┆ on_2b ┆ next_on_2 ┆ steal_suc ┆ throw_res │
│ g          ┆ ame        ┆ ---       ┆ ---        ┆   ┆ ---   ┆ b         ┆ cessful   ┆ ults      │
│ ---        ┆ ---        ┆ i64       ┆ f64        ┆   ┆ str   ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆           ┆            ┆   ┆       ┆ str       ┆ bool      ┆ i32       │
╞════════════╪════════════╪═══════════╪════════════╪═══╪═══════╪═══════════╪═══════════╪═══════════╡
│ y1_d123_IO ┆ 98         ┆ 100       ┆ 1.95       ┆ … ┆ NA    ┆ NA        ┆ false     ┆ 0         │
│ L_VAS      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d190_PH ┆ 160        ┆ 161       ┆ 2.48       ┆ … ┆ NA    ┆ PHD-1580  ┆ true      ┆ 0         │
│ D_ARN      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d105_MS ┆ 9          ┆ 10        ┆ 2.2        ┆ … ┆ NA    ┆ NA        ┆ false     ┆ 0         │
│ N_VAS      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d106_MS ┆ 305        ┆ 306       ┆ 2.45       ┆ … ┆ NA    ┆ NA        ┆ false     ┆ 0         │
│ N_VAS      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d117_BX ┆ 50         ┆ 52        ┆ 2.05       ┆ … ┆ NA    ┆ NA        ┆ false     ┆ 0         │
│ H_VAS      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d083_RY ┆ 123        ┆ 124       ┆ 1.45       ┆ … ┆ NA    ┆ RYU-4519  ┆ true      ┆ 0         │
│ U_PHD      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d138_HY ┆ 11         ┆ 12        ┆ 2.11       ┆ … ┆ NA    ┆ HYG-0835  ┆ true      ┆ 0         │
│ G_PHD      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d094_NF ┆ 139        ┆ 140       ┆ 2.2        ┆ … ┆ NA    ┆ NA        ┆ false     ┆ 0         │
│ P_PHD      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d072_UR ┆ 211        ┆ 213       ┆ 2.1        ┆ … ┆ NA    ┆ NA        ┆ false     ┆ 0         │
│ D_ARN      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
│ y1_d119_MK ┆ 290        ┆ 291       ┆ null       ┆ … ┆ NA    ┆ NA        ┆ false     ┆ 1         │
│ S_ARN      ┆            ┆           ┆            ┆   ┆       ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────────┴───┴───────┴───────────┴───────────┴───────────┘

In [41]:
final_df.shape

(116, 15)

In [42]:
throw_results_count = final_df.filter(pl.col("throw_results") == 1)

throw_results_count.shape

(9, 15)

In [43]:
x_y_df = final_df.select("throw_time", "2nd_baseman_field_x", "2nd_baseman_field_y", "steal_successful", "throw_results")

x_y_df.drop_nulls()
X = x_y_df.drop("steal_successful")
y = x_y_df["steal_successful"]
X = X.to_pandas()
y = y.to_pandas()
y = y.astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, train_size= .8, random_state = 42, stratify = y)

In [44]:
grid_search = {"max_depth": range(1, 16), "max_leaf_nodes": range(2, 21), "min_samples_leaf": range(1, 10)}

decision_tree = DecisionTreeClassifier(random_state = 42)

grid = GridSearchCV(decision_tree, grid_search, cv = 5, scoring = "roc_auc")

grid.fit(X_train, y_train)
print(grid.best_params_)
print(grid.best_score_)
best_tree = grid.best_estimator_

{'max_depth': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1}
0.640422077922078

In [45]:
print(export_text(
    best_tree,
    feature_names=list(X.columns)
))

|--- throw_time <= 2.32
|   |--- throw_time <= 1.65
|   |   |--- class: 1
|   |--- throw_time >  1.65
|   |   |--- class: 0
|--- throw_time >  2.32
|   |--- 2nd_baseman_field_y <= 142.70
|   |   |--- class: 0
|   |--- 2nd_baseman_field_y >  142.70
|   |   |--- class: 1

In [46]:
importance = (
    pd.DataFrame({
        "feature": X.columns,
        "importance": best_tree.feature_importances_
    })
    .sort_values("importance", ascending=False)
)

importance

               feature  importance
0           throw_time    0.744803
2  2nd_baseman_field_y    0.255197
1  2nd_baseman_field_x    0.000000
3        throw_results    0.000000

In [47]:
game_filter = lineups_df.filter(
    (pl.col("game_string") == "y1_d184_WIF_ANI"),
    (pl.col("play_per_game").is_in([207, 208]))
    )
game_filter

shape: (2, 21)
┌─────────────────┬────────┬─────────────┬───────────┬───┬──────────┬──────────┬───────┬───────┐
│ game_string     ┆ inning ┆ half_inning ┆ home_team ┆ … ┆ batter   ┆ on_1b    ┆ on_2b ┆ on_3b │
│ ---             ┆ ---    ┆ ---         ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---   ┆ ---   │
│ str             ┆ i64    ┆ str         ┆ str       ┆   ┆ str      ┆ str      ┆ str   ┆ str   │
╞═════════════════╪════════╪═════════════╪═══════════╪═══╪══════════╪══════════╪═══════╪═══════╡
│ y1_d184_WIF_ANI ┆ 7      ┆ Top         ┆ ANI       ┆ … ┆ WIF-0714 ┆ WIF-2990 ┆ NA    ┆ NA    │
│ y1_d184_WIF_ANI ┆ 7      ┆ Top         ┆ ANI       ┆ … ┆ WIF-0714 ┆ WIF-2990 ┆ NA    ┆ NA    │
└─────────────────┴────────┴─────────────┴───────────┴───┴──────────┴──────────┴───────┴───────┘