In [525]:
import polars as pl
import pandas as pd 
import numpy as np
import os
import pyarrow.dataset as pads

from sklearn.metrics import mean_squared_error,root_mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import RepeatedKFold,GridSearchCV,RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor

import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter

import seaborn as sns

In [ ]:
def readDataSubset(table_type, data_path = ""):
    if table_type not in ["ball-positions", "ball-events", "player-positions", 'lineups', "game-info"]:
        print("I dont think so")
        return -1
    if table_type == 'lineups' or table_type == "game_info":
        return pads.dataset(source = os.path.join(os.path.dirname(__name__), data_path, table_type + '.csv'), format = 'csv')
    else:
        return pads.dataset(source = os.path.join(os.path.dirname(__name__), data_path, table_type), format = 'csv', partitioning = ['home_team', 'away_team', 'year', 'day'])

In [527]:
# Read Ball Events Data
ball_events_subset = readDataSubset('ball-events')
ball_events = ball_events_subset.to_table().to_pandas()
ball_events_df = pl.from_pandas(ball_events)

# Read Lineups Data
lineups_subset = readDataSubset('lineups')
lineups = lineups_subset.to_table().to_pandas()
lineups_df = pl.from_pandas(lineups)

# Read Player Positions
player_pos_subset = readDataSubset('player-positions')
player_positions_11 = player_pos_subset.to_table(filter = ((pads.field("player_id") == 11))).to_pandas()
player_pos_11_df = pl.from_pandas(player_positions_11)

# Read Player Positions
player_positions_12 = player_pos_subset.to_table(filter = ((pads.field("player_id") == 12))).to_pandas()
player_pos_12_df = pl.from_pandas(player_positions_12)

# Read Player Positions
player_positions_2bm = player_pos_subset.to_table(filter = ((pads.field("player_id") == 4))).to_pandas()
player_pos_2bm_df = pl.from_pandas(player_positions_2bm)

# Read Player Positions
player_positions_ss = player_pos_subset.to_table(filter = ((pads.field("player_id") == 6))).to_pandas()
player_pos_ss_df = pl.from_pandas(player_positions_ss)

In [528]:
cleaned_11_df = player_pos_11_df.sort(
    ['game_string', 'play_per_game', 'timestamp']
).select(
    ['game_string', 'play_per_game', pl.col('timestamp').alias("1b_timestamp"),
    pl.col("field_x").alias("1b_field_x"), pl.col("field_y").alias("1b_field_y")]
)

cleaned_12_df = player_pos_12_df.sort(
    ['game_string', 'play_per_game', 'timestamp']
).select(
    ['game_string', 'play_per_game', pl.col('timestamp').alias("2b_timestamp"),
    pl.col("field_x").alias("2b_field_x"), pl.col("field_y").alias("2b_field_y")]
)

cleaned_10_df = player_pos_2bm_df.sort(
    ['game_string', 'play_per_game', 'timestamp']
).select(
    ['game_string', 'play_per_game', pl.col('timestamp').alias("2bm_timestamp"),
    pl.col("field_x").alias("2bm_field_x"), pl.col("field_y").alias("2bm_field_y")]
)

In [529]:
player_positions_df = pl.concat([cleaned_11_df, cleaned_12_df, cleaned_10_df], how = "diagonal").group_by(
        ["game_string", "play_per_game"]
).agg(
    pl.col("1b_field_x").mean(),
    pl.col("1b_field_y").mean(),
    pl.col("2b_field_x").mean(),
    pl.col("2b_field_y").mean(),
    pl.col("2bm_field_x").mean(),
    pl.col("2bm_field_y").mean(),
    pl.col("1b_timestamp").min(),
    pl.col("2b_timestamp").min(),
    pl.col("2bm_timestamp").min()
).with_columns(
    (pl.col("1b_field_x")).alias("on_1b"),
    (pl.col("2b_field_x")).alias("on_2b"),
    play_per_game = pl.col("play_per_game").cast(pl.Int64)
).select(
    ["game_string", "play_per_game", "2bm_field_x", "2bm_field_y", "1b_field_x", "1b_field_y", "2b_field_x", "2b_field_y", "on_1b", "on_2b", "1b_timestamp", "2b_timestamp", "2bm_timestamp"]
).sort(
    ["game_string", "play_per_game"]
)

In [530]:
player_positions_df = player_positions_df.with_columns(
        on_1b = pl.col("on_1b").cast(pl.Boolean),
        on_2b = pl.col("on_2b").cast(pl.Boolean)
)

In [531]:
player_positions_df = player_positions_df.with_columns(
    on_1b = pl.when(pl.col("on_1b").is_null()).then(pl.lit(False)).otherwise(pl.lit(True)),
    on_2b = pl.when(pl.col("on_2b").is_null()).then(pl.lit(False)).otherwise(pl.lit(True))
)

In [533]:
player_positions_df.head(10)

shape: (10, 13)
┌────────────┬────────────┬────────────┬───────────┬───┬───────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ 2bm_field_ ┆ 2bm_field ┆ … ┆ on_2b ┆ 1b_timest ┆ 2b_timest ┆ 2bm_times │
│ g          ┆ ame        ┆ x          ┆ _y        ┆   ┆ ---   ┆ amp       ┆ amp       ┆ tamp      │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ bool  ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆ f64        ┆ f64       ┆   ┆       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════╪═══════════╪═══════════╪═══════════╡
│ NA         ┆ null       ┆ 30.265505  ┆ 142.22409 ┆ … ┆ true  ┆ null      ┆ null      ┆ null      │
│            ┆            ┆            ┆ 5         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 1          ┆ 45.2952    ┆ 134.77536 ┆ … ┆ false ┆ null      ┆ null      ┆ 63614.0   │
│ A_PHD      ┆            ┆            ┆           ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 2          ┆ 38.727397  ┆ 139.78724 ┆ … ┆ false ┆ null      ┆ null      ┆ 72964.0   │
│ A_PHD      ┆            ┆            ┆ 6         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 3          ┆ 80.590907  ┆ 154.86824 ┆ … ┆ false ┆ null      ┆ null      ┆ 106614.0  │
│ A_PHD      ┆            ┆            ┆ 7         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 4          ┆ 56.397807  ┆ 142.55021 ┆ … ┆ false ┆ null      ┆ null      ┆ 142414.0  │
│ A_PHD      ┆            ┆            ┆ 4         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 5          ┆ 57.398725  ┆ 142.00687 ┆ … ┆ false ┆ null      ┆ null      ┆ 155864.0  │
│ A_PHD      ┆            ┆            ┆ 2         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 6          ┆ 57.98781   ┆ 142.25429 ┆ … ┆ false ┆ null      ┆ null      ┆ 170114.0  │
│ A_PHD      ┆            ┆            ┆ 6         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 7          ┆ 56.105501  ┆ 141.71868 ┆ … ┆ false ┆ null      ┆ null      ┆ 187114.0  │
│ A_PHD      ┆            ┆            ┆ 2         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 8          ┆ 44.058538  ┆ 142.77530 ┆ … ┆ false ┆ null      ┆ null      ┆ 212564.0  │
│ A_PHD      ┆            ┆            ┆ 3         ┆   ┆       ┆           ┆           ┆           │
│ y1_d061_VK ┆ 9          ┆ 58.168056  ┆ 139.63366 ┆ … ┆ false ┆ null      ┆ null      ┆ 367464.0  │
│ A_PHD      ┆            ┆            ┆ 1         ┆   ┆       ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴───────┴───────────┴───────────┴───────────┘

In [534]:
player_positions_df.shape

(74043, 13)

In [535]:
relevant_game_string = player_positions_df["game_string"]
relevant_ppg = player_positions_df["play_per_game"]
# Read Lineups Data
lineups_subset = readDataSubset('lineups')
cf_position = lineups_subset.to_table(filter = ((pads.field('game_string').isin(relevant_game_string)) & 
                                                    (pads.field('play_per_game').isin(relevant_ppg)))).to_pandas()
lineups_df = pl.from_pandas(lineups)

In [536]:
lineups_df = lineups_df.select(
    ["game_string", "play_per_game", "at_bat"]
)

In [537]:
steals = player_positions_df.join(
    lineups_df, on = ["game_string", "play_per_game"], how = "left"
).sort(
    ["game_string", "play_per_game"]
).select(
    ["game_string", "play_per_game", "at_bat", "2bm_field_x", "2bm_field_y", "1b_field_x", "1b_field_y", "2b_field_x", "2b_field_y", "on_1b", "on_2b", "1b_timestamp", "2b_timestamp", "2bm_timestamp"]
)

steals.head()

shape: (5, 14)
┌────────────┬────────────┬────────┬────────────┬───┬───────┬────────────┬────────────┬────────────┐
│ game_strin ┆ play_per_g ┆ at_bat ┆ 2bm_field_ ┆ … ┆ on_2b ┆ 1b_timesta ┆ 2b_timesta ┆ 2bm_timest │
│ g          ┆ ame        ┆ ---    ┆ x          ┆   ┆ ---   ┆ mp         ┆ mp         ┆ amp        │
│ ---        ┆ ---        ┆ i64    ┆ ---        ┆   ┆ bool  ┆ ---        ┆ ---        ┆ ---        │
│ str        ┆ i64        ┆        ┆ f64        ┆   ┆       ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪════════════╪════════╪════════════╪═══╪═══════╪════════════╪════════════╪════════════╡
│ NA         ┆ null       ┆ null   ┆ 30.265505  ┆ … ┆ true  ┆ null       ┆ null       ┆ null       │
│ y1_d061_VK ┆ 1          ┆ 1      ┆ 45.2952    ┆ … ┆ false ┆ null       ┆ null       ┆ 63614.0    │
│ A_PHD      ┆            ┆        ┆            ┆   ┆       ┆            ┆            ┆            │
│ y1_d061_VK ┆ 2          ┆ 1      ┆ 38.727397  ┆ … ┆ false ┆ null       ┆ null       ┆ 72964.0    │
│ A_PHD      ┆            ┆        ┆            ┆   ┆       ┆            ┆            ┆            │
│ y1_d061_VK ┆ 3          ┆ 2      ┆ 80.590907  ┆ … ┆ false ┆ null       ┆ null       ┆ 106614.0   │
│ A_PHD      ┆            ┆        ┆            ┆   ┆       ┆            ┆            ┆            │
│ y1_d061_VK ┆ 4          ┆ 3      ┆ 56.397807  ┆ … ┆ false ┆ null       ┆ null       ┆ 142414.0   │
│ A_PHD      ┆            ┆        ┆            ┆   ┆       ┆            ┆            ┆            │
└────────────┴────────────┴────────┴────────────┴───┴───────┴────────────┴────────────┴────────────┘

In [538]:
successful_steals = steals.with_columns(
    (pl.col("at_bat").shift(-1)).alias("next_at_bat"),
    (pl.col("on_1b").shift(-1)).alias("next_on_1b"),
    (pl.col("on_2b").shift(-1)).alias("next_on_2b"),
    (pl.col("1b_field_x").shift(-1)).alias("next_1b_x"),
    (pl.col("1b_field_y").shift(-1)).alias("next_1b_y"),
    (pl.col("1b_timestamp").shift(-1)).alias("next_1b_time"),
    (pl.col("2b_field_x").shift(-1)).alias("next_2b_x"),
    (pl.col("2b_field_y").shift(-1)).alias("next_2b_y"),
    (pl.col("2b_timestamp").shift(-1)).alias("next_2b_time"),
    (pl.col("2bm_field_x").shift(1)).alias("pre_2bm_field_x"),
    (pl.col("2bm_field_y").shift(1)).alias("pre_2bm_field_y"),
    (pl.col("2bm_timestamp").shift(1)).alias("pre_2bm_timestamp")
).filter(
    (pl.col("at_bat") == pl.col("next_at_bat")) &
    (pl.col("on_1b") == True) &
    (pl.col("next_on_1b") == False) &
    (pl.col("next_on_2b") == True)
).with_columns(
    (pl.lit(1).alias("steal_successful"))
)

successful_steals.head()

shape: (5, 27)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ at_bat ┆ 2bm_field ┆ … ┆ pre_2bm_f ┆ pre_2bm_f ┆ pre_2bm_t ┆ steal_suc │
│ g          ┆ ame        ┆ ---    ┆ _x        ┆   ┆ ield_x    ┆ ield_y    ┆ imestamp  ┆ cessful   │
│ ---        ┆ ---        ┆ i64    ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ i32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 213        ┆ 59     ┆ -8.948758 ┆ … ┆ -14.77433 ┆ 149.26437 ┆ 7.036714e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆ 3         ┆ 5         ┆ 6         ┆           │
│ y1_d062_VK ┆ 230        ┆ 53     ┆ 55.694929 ┆ … ┆ 61.461092 ┆ 121.55183 ┆ 7.006084e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 8         ┆ 6         ┆           │
│ y1_d063_VK ┆ 253        ┆ 67     ┆ 30.047615 ┆ … ┆ 39.165271 ┆ 147.66826 ┆ 8.199265e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 3         ┆ 6         ┆           │
│ y1_d064_VK ┆ 80         ┆ 19     ┆ 17.550415 ┆ … ┆ 24.392722 ┆ 146.35625 ┆ 2.343139e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 6         ┆           │
│ y1_d064_VK ┆ 177        ┆ 42     ┆ 85.860747 ┆ … ┆ 88.400831 ┆ 156.37193 ┆ 5.522923e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 7         ┆ 6         ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [539]:
print(successful_steals.shape)

(462, 27)

In [542]:
failed_steals = steals.with_columns(
    (pl.col("at_bat").shift(-1)).alias("next_at_bat"),
    (pl.col("on_1b").shift(-1)).alias("next_on_1b"),
    (pl.col("on_2b").shift(-1)).alias("next_on_2b"),
    (pl.col("1b_field_x").shift(-1)).alias("next_1b_x"),
    (pl.col("1b_field_y").shift(-1)).alias("next_1b_y"),
    (pl.col("1b_timestamp").shift(-1)).alias("next_1b_time"),
    (pl.col("2b_field_x").shift(-1)).alias("next_2b_x"),
    (pl.col("2b_field_y").shift(-1)).alias("next_2b_y"),
    (pl.col("2b_timestamp").shift(-1)).alias("next_2b_time"),
    (pl.col("2bm_field_x").shift(1)).alias("pre_2bm_field_x"),
    (pl.col("2bm_field_y").shift(1)).alias("pre_2bm_field_y"),
    (pl.col("2bm_timestamp").shift(1)).alias("pre_2bm_timestamp")
).filter(
    (pl.col("at_bat") == pl.col("next_at_bat")) &
    (pl.col("on_1b") == True) &
    (pl.col("next_on_1b") == False) &
    (pl.col("next_on_2b") == False)
).with_columns(
    (pl.lit(0)).alias("steal_successful")
)

failed_steals.head()

shape: (5, 27)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ at_bat ┆ 2bm_field ┆ … ┆ pre_2bm_f ┆ pre_2bm_f ┆ pre_2bm_t ┆ steal_suc │
│ g          ┆ ame        ┆ ---    ┆ _x        ┆   ┆ ield_x    ┆ ield_y    ┆ imestamp  ┆ cessful   │
│ ---        ┆ ---        ┆ i64    ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ i32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 106        ┆ 33     ┆ 14.220055 ┆ … ┆ 28.918463 ┆ 134.45314 ┆ 3.335664e ┆ 0         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 8         ┆ 6         ┆           │
│ y1_d063_VK ┆ 200        ┆ 56     ┆ 20.057146 ┆ … ┆ 19.59941  ┆ 145.59229 ┆ 6.579765e ┆ 0         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 6         ┆           │
│ y1_d065_VA ┆ 13         ┆ 4      ┆ -13.42967 ┆ … ┆ 51.523045 ┆ 123.85490 ┆ 221505.0  ┆ 0         │
│ S_PHD      ┆            ┆        ┆ 3         ┆   ┆           ┆ 6         ┆           ┆           │
│ y1_d065_VA ┆ 62         ┆ 16     ┆ 12.614919 ┆ … ┆ 10.950813 ┆ 141.72378 ┆ 1.972387e ┆ 0         │
│ S_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 5         ┆ 6         ┆           │
│ y1_d067.5_ ┆ 129        ┆ 32     ┆ 49.171023 ┆ … ┆ 36.494687 ┆ 151.98638 ┆ 4.174581e ┆ 0         │
│ NLG_ANI    ┆            ┆        ┆           ┆   ┆           ┆ 9         ┆ 6         ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [543]:
final_steal_df = pl.concat([successful_steals, failed_steals], how = "vertical").sort(["game_string", "play_per_game"])

final_steal_df.head()

shape: (5, 27)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ at_bat ┆ 2bm_field ┆ … ┆ pre_2bm_f ┆ pre_2bm_f ┆ pre_2bm_t ┆ steal_suc │
│ g          ┆ ame        ┆ ---    ┆ _x        ┆   ┆ ield_x    ┆ ield_y    ┆ imestamp  ┆ cessful   │
│ ---        ┆ ---        ┆ i64    ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ i32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 106        ┆ 33     ┆ 14.220055 ┆ … ┆ 28.918463 ┆ 134.45314 ┆ 3.335664e ┆ 0         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 8         ┆ 6         ┆           │
│ y1_d061_VK ┆ 213        ┆ 59     ┆ -8.948758 ┆ … ┆ -14.77433 ┆ 149.26437 ┆ 7.036714e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆ 3         ┆ 5         ┆ 6         ┆           │
│ y1_d062_VK ┆ 230        ┆ 53     ┆ 55.694929 ┆ … ┆ 61.461092 ┆ 121.55183 ┆ 7.006084e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 8         ┆ 6         ┆           │
│ y1_d063_VK ┆ 200        ┆ 56     ┆ 20.057146 ┆ … ┆ 19.59941  ┆ 145.59229 ┆ 6.579765e ┆ 0         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 6         ┆           │
│ y1_d063_VK ┆ 253        ┆ 67     ┆ 30.047615 ┆ … ┆ 39.165271 ┆ 147.66826 ┆ 8.199265e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 3         ┆ 6         ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [544]:
print(final_steal_df.shape)
final_steal_df.describe()

(654, 27)

shape: (9, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ game_stri ┆ play_per_ ┆ at_bat    ┆ … ┆ pre_2bm_f ┆ pre_2bm_f ┆ pre_2bm_t ┆ steal_su │
│ ---       ┆ ng        ┆ game      ┆ ---       ┆   ┆ ield_x    ┆ ield_y    ┆ imestamp  ┆ ccessful │
│ str       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 654       ┆ 654.0     ┆ 654.0     ┆ … ┆ 654.0     ┆ 654.0     ┆ 654.0     ┆ 654.0    │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 172.46789 ┆ 43.310398 ┆ … ┆ 30.383798 ┆ 141.55794 ┆ 6.4223e6  ┆ 0.706422 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 1         ┆           ┆          │
│ std       ┆ null      ┆ 97.910692 ┆ 24.240689 ┆ … ┆ 20.993214 ┆ 9.229608  ┆ 7.2896e6  ┆ 0.455749 │
│ min       ┆ y1_d061_V ┆ 2.0       ┆ 1.0       ┆ … ┆ -26.59127 ┆ 105.54268 ┆ 6411.0    ┆ 0.0      │
│           ┆ KA_PHD    ┆           ┆           ┆   ┆ 8         ┆ 6         ┆           ┆          │
│ 25%       ┆ null      ┆ 85.0      ┆ 22.0      ┆ … ┆ 17.331803 ┆ 136.33556 ┆ 2.796745e ┆ 0.0      │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 6         ┆          │
│ 50%       ┆ null      ┆ 173.0     ┆ 44.0      ┆ … ┆ 27.320903 ┆ 142.18876 ┆ 5.715412e ┆ 1.0      │
│           ┆           ┆           ┆           ┆   ┆           ┆ 5         ┆ 6         ┆          │
│ 75%       ┆ null      ┆ 249.0     ┆ 63.0      ┆ … ┆ 45.770691 ┆ 147.54412 ┆ 8.511993e ┆ 1.0      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6         ┆          │
│ max       ┆ y1_d217_V ┆ 399.0     ┆ 98.0      ┆ … ┆ 106.89130 ┆ 202.25341 ┆ 7.5116163 ┆ 1.0      │
│           ┆ AS_ARN    ┆           ┆           ┆   ┆ 8         ┆ 9         ┆ e7        ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [547]:
catcher_events_to_2bm = ball_events_df.sort(
    ["game_string", "play_per_game", "timestamp"]
).filter(
    (pl.col("player_id") == 1) &
    (pl.col("ball_eventcode") == 1) &
    (pl.col("player_id").shift(-1) == 2) &
    (pl.col("ball_eventcode").shift(-1) == 2) &
    (pl.col("player_id").shift(-2) == 2) &
    (pl.col("ball_eventcode").shift(-2) == 3) &
    (pl.col("player_id").shift(-3) == 4) &
    (pl.col("ball_eventcode").shift(-3) == 2)
    .over(["game_string", "play_per_game"])
).select(
    ["game_string", "play_per_game", pl.col("timestamp").alias("throw_time"), pl.lit(1).alias("2bm")]
)

ball_events_2bm = ball_events_df.sort(
    ["game_string", "play_per_game", "timestamp"]
).filter(
    (pl.col("player_id").shift(1) == 2) &
    (pl.col("ball_eventcode").shift(1) == 3) &
    (pl.col("player_id") == 4) &
    (pl.col("ball_eventcode") == 2)
    .over(["game_string", "play_per_game"])
).select(
    ["game_string", "play_per_game", pl.col("timestamp").alias("catch_time"), pl.lit(1).alias("2bm")]
)

catcher_events_to_ss = ball_events_df.sort(
    ["game_string", "play_per_game", "timestamp"]
).filter(
    (pl.col("player_id") == 1) &
    (pl.col("ball_eventcode") == 1) &
    (pl.col("player_id").shift(-1) == 2) &
    (pl.col("ball_eventcode").shift(-1) == 2) &
    (pl.col("player_id").shift(-2) == 2) &
    (pl.col("ball_eventcode").shift(-2) == 3) &
    (pl.col("player_id").shift(-3) == 6) &
    (pl.col("ball_eventcode").shift(-3) == 2)
    .over(["game_string", "play_per_game"])
).select(
    ["game_string", "play_per_game", pl.col("timestamp").alias("throw_time"), pl.lit(1).alias("ss")]
)

ball_events_ss = ball_events_df.sort(
    ["game_string", "play_per_game", "timestamp"]
).filter(
    (pl.col("player_id").shift(1) == 2) &
    (pl.col("ball_eventcode").shift(1) == 3) &
    (pl.col("player_id") == 6) &
    (pl.col("ball_eventcode") == 2)
    .over(["game_string", "play_per_game"])
).select(
    ["game_string", "play_per_game", pl.col("timestamp").alias("catch_time"), pl.lit(1).alias("ss")]
)

In [548]:
catcher_steals = pl.concat([catcher_events_to_2bm, ball_events_2bm, catcher_events_to_ss, ball_events_ss], how = "diagonal").group_by(
    ["game_string", "play_per_game", "2bm", "ss"]
).agg(
    pl.col("throw_time").min(),
    pl.col("catch_time").min()
).with_columns(
    throw_time = ((pl.col("catch_time") - pl.col("throw_time")) / 1000).round(2),
    play_per_game = pl.col("play_per_game").cast(pl.Int64)
).sort(
    ["game_string", "play_per_game"]
).select(
    ["game_string", "play_per_game", "throw_time", "2bm", "ss"]
).drop_nulls("play_per_game").drop_nulls("throw_time").fill_null(0)

catcher_steals.head()

shape: (5, 5)
┌─────────────────┬───────────────┬────────────┬─────┬─────┐
│ game_string     ┆ play_per_game ┆ throw_time ┆ 2bm ┆ ss  │
│ ---             ┆ ---           ┆ ---        ┆ --- ┆ --- │
│ str             ┆ i64           ┆ f64        ┆ i32 ┆ i32 │
╞═════════════════╪═══════════════╪════════════╪═════╪═════╡
│ y1_d061_VKA_PHD ┆ 106           ┆ 2.35       ┆ 1   ┆ 0   │
│ y1_d064_VKA_PHD ┆ 177           ┆ 2.57       ┆ 0   ┆ 1   │
│ y1_d065_VAS_PHD ┆ 80            ┆ 2.41       ┆ 1   ┆ 0   │
│ y1_d070_SQF_ARN ┆ 167           ┆ 2.38       ┆ 0   ┆ 1   │
│ y1_d071_SQF_ARN ┆ 278           ┆ 2.31       ┆ 0   ┆ 1   │
└─────────────────┴───────────────┴────────────┴─────┴─────┘

In [551]:
catcher_steals.sample(n = 10)

shape: (10, 5)
┌─────────────────┬───────────────┬────────────┬─────┬─────┐
│ game_string     ┆ play_per_game ┆ throw_time ┆ 2bm ┆ ss  │
│ ---             ┆ ---           ┆ ---        ┆ --- ┆ --- │
│ str             ┆ i64           ┆ f64        ┆ i32 ┆ i32 │
╞═════════════════╪═══════════════╪════════════╪═════╪═════╡
│ y1_d201_JGO_VAS ┆ 76            ┆ 2.65       ┆ 0   ┆ 1   │
│ y1_d211_PHD_VAS ┆ 59            ┆ 2.9        ┆ 0   ┆ 1   │
│ y1_d168_MPC_PHD ┆ 58            ┆ 2.4        ┆ 1   ┆ 0   │
│ y1_d162_KZR_VAS ┆ 59            ┆ 2.4        ┆ 1   ┆ 0   │
│ y1_d166_SZJ_ANI ┆ 183           ┆ 2.45       ┆ 0   ┆ 1   │
│ y1_d124_VAS_PHD ┆ 93            ┆ 2.4        ┆ 0   ┆ 1   │
│ y1_d167_MPC_PHD ┆ 11            ┆ 2.4        ┆ 0   ┆ 1   │
│ y1_d148_VHA_PHD ┆ 202           ┆ 2.34       ┆ 0   ┆ 1   │
│ y1_d179_YXL_PHD ┆ 195           ┆ 2.6        ┆ 0   ┆ 1   │
│ y1_d150_VNG_VAS ┆ 150           ┆ 2.35       ┆ 1   ┆ 0   │
└─────────────────┴───────────────┴────────────┴─────┴─────┘

In [458]:
player_positions_2bm

,game_string,play_per_game,timestamp,player_id,field_x,field_y,home_team,away_team,year,day
0,y1_d143_ADQ_ANI,1.0,50804.0,4,41.1609,148.5990,ANI,ADQ,y1,d143
1,y1_d143_ADQ_ANI,1.0,50854.0,4,41.1546,148.5960,ANI,ADQ,y1,d143
2,y1_d143_ADQ_ANI,1.0,50904.0,4,41.1480,148.5927,ANI,ADQ,y1,d143
3,y1_d143_ADQ_ANI,1.0,50954.0,4,41.1414,148.5897,ANI,ADQ,y1,d143
4,y1_d143_ADQ_ANI,1.0,51004.0,4,41.1345,148.5867,ANI,ADQ,y1,d143
...,...,...,...,...,...,...,...,...,...,...
7617753,y1_d103_WTH_VAS,306.0,10163985.0,4,-5.6718,148.5492,VAS,WTH,y1,d103
7617754,y1_d103_WTH_VAS,306.0,10164035.0,4,-5.6442,148.2768,VAS,WTH,y1,d103
7617755,y1_d103_WTH_VAS,306.0,10164085.0,4,-5.6163,148.0020,VAS,WTH,y1,d103
7617756,y1_d103_WTH_VAS,306.0,10164135.0,4,-5.5881,147.7260,VAS,WTH,y1,d103
7617757,y1_d103_WTH_VAS,306.0,10164185.0,4,-5.5602,147.4494,VAS,WTH,y1,d103

In [460]:
player_pos_2bm_df.head()

shape: (5, 10)
┌─────────────┬─────────────┬─────┬───────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ game_string ┆ play_per_ga ┆ 2bm ┆ timestamp ┆ … ┆ pre_ppg ┆ pre_field_ ┆ pre_field_ ┆ pre_timest │
│ ---         ┆ me          ┆ --- ┆ ---       ┆   ┆ ---     ┆ x          ┆ y          ┆ amp        │
│ str         ┆ ---         ┆ i32 ┆ f64       ┆   ┆ i64     ┆ ---        ┆ ---        ┆ ---        │
│             ┆ i64         ┆     ┆           ┆   ┆         ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════╪═══════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ NA          ┆ null        ┆ 1   ┆ null      ┆ … ┆ null    ┆ null       ┆ null       ┆ null       │
│ y1_d061_VKA ┆ 1           ┆ 1   ┆ 63614.0   ┆ … ┆ null    ┆ 30.265505  ┆ 142.224095 ┆ null       │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 2           ┆ 1   ┆ 72964.0   ┆ … ┆ 1       ┆ 45.2952    ┆ 134.77536  ┆ 63614.0    │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 3           ┆ 1   ┆ 106614.0  ┆ … ┆ 2       ┆ 38.727397  ┆ 139.787246 ┆ 72964.0    │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 4           ┆ 1   ┆ 142414.0  ┆ … ┆ 3       ┆ 80.590907  ┆ 154.868247 ┆ 106614.0   │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
└─────────────┴─────────────┴─────┴───────────┴───┴─────────┴────────────┴────────────┴────────────┘

In [552]:
player_pos_2bm_df = player_pos_2bm_df.with_columns(play_per_game = pl.col("play_per_game").cast(pl.Int64)).select(
    ["game_string", "play_per_game", "timestamp", "field_x", "field_y", pl.lit(1).alias("2bm")]
)
player_pos_ss_df = player_pos_ss_df.with_columns(play_per_game = pl.col("play_per_game").cast(pl.Int64)).select(
    ["game_string", "play_per_game", "timestamp", "field_x", "field_y", pl.lit(1).alias("ss")]
)

In [553]:
player_pos_2bm_df.head()

shape: (5, 6)
┌─────────────────┬───────────────┬───────────┬─────────┬──────────┬─────┐
│ game_string     ┆ play_per_game ┆ timestamp ┆ field_x ┆ field_y  ┆ 2bm │
│ ---             ┆ ---           ┆ ---       ┆ ---     ┆ ---      ┆ --- │
│ str             ┆ i64           ┆ f64       ┆ f64     ┆ f64      ┆ i32 │
╞═════════════════╪═══════════════╪═══════════╪═════════╪══════════╪═════╡
│ y1_d143_ADQ_ANI ┆ 1             ┆ 50804.0   ┆ 41.1609 ┆ 148.599  ┆ 1   │
│ y1_d143_ADQ_ANI ┆ 1             ┆ 50854.0   ┆ 41.1546 ┆ 148.596  ┆ 1   │
│ y1_d143_ADQ_ANI ┆ 1             ┆ 50904.0   ┆ 41.148  ┆ 148.5927 ┆ 1   │
│ y1_d143_ADQ_ANI ┆ 1             ┆ 50954.0   ┆ 41.1414 ┆ 148.5897 ┆ 1   │
│ y1_d143_ADQ_ANI ┆ 1             ┆ 51004.0   ┆ 41.1345 ┆ 148.5867 ┆ 1   │
└─────────────────┴───────────────┴───────────┴─────────┴──────────┴─────┘

In [554]:
player_pos_2bm_df = player_pos_2bm_df.group_by(["game_string", "play_per_game", "2bm"]
).agg(
    pl.col("timestamp").min(),
    pl.col("field_x").mean(),
    pl.col("field_y").mean()
).sort(["game_string", "play_per_game"])

player_pos_ss_df = player_pos_ss_df.group_by(["game_string", "play_per_game", "ss"]
).agg(
    pl.col("timestamp").min(),
    pl.col("field_x").mean(),
    pl.col("field_y").mean()
).sort(["game_string", "play_per_game"])

In [555]:
player_pos_2bm_df = player_pos_2bm_df.with_columns(
    pl.col("play_per_game").shift(1).alias("pre_ppg"), 
    pl.col("field_x").shift(1).alias("pre_field_x"),
    pl.col("field_y").shift(1).alias("pre_field_y"),
    pl.col("timestamp").shift(1).alias("pre_timestamp")
)
player_pos_2bm_df

shape: (74_043, 10)
┌─────────────┬────────────┬─────┬────────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ game_string ┆ play_per_g ┆ 2bm ┆ timestamp  ┆ … ┆ pre_ppg ┆ pre_field_ ┆ pre_field_ ┆ pre_timest │
│ ---         ┆ ame        ┆ --- ┆ ---        ┆   ┆ ---     ┆ x          ┆ y          ┆ amp        │
│ str         ┆ ---        ┆ i32 ┆ f64        ┆   ┆ i64     ┆ ---        ┆ ---        ┆ ---        │
│             ┆ i64        ┆     ┆            ┆   ┆         ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪════════════╪═════╪════════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ NA          ┆ null       ┆ 1   ┆ null       ┆ … ┆ null    ┆ null       ┆ null       ┆ null       │
│ y1_d061_VKA ┆ 1          ┆ 1   ┆ 63614.0    ┆ … ┆ null    ┆ 30.265505  ┆ 142.224095 ┆ null       │
│ _PHD        ┆            ┆     ┆            ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 2          ┆ 1   ┆ 72964.0    ┆ … ┆ 1       ┆ 45.2952    ┆ 134.77536  ┆ 63614.0    │
│ _PHD        ┆            ┆     ┆            ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 3          ┆ 1   ┆ 106614.0   ┆ … ┆ 2       ┆ 38.727397  ┆ 139.787246 ┆ 72964.0    │
│ _PHD        ┆            ┆     ┆            ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 4          ┆ 1   ┆ 142414.0   ┆ … ┆ 3       ┆ 80.590907  ┆ 154.868247 ┆ 106614.0   │
│ _PHD        ┆            ┆     ┆            ┆   ┆         ┆            ┆            ┆            │
│ …           ┆ …          ┆ …   ┆ …          ┆ … ┆ …       ┆ …          ┆ …          ┆ …          │
│ y1_d217_VAS ┆ 347        ┆ 1   ┆ 1.1134986e ┆ … ┆ 346     ┆ 19.085584  ┆ 143.88822  ┆ 1.1111436e │
│ _ARN        ┆            ┆     ┆ 7          ┆   ┆         ┆            ┆            ┆ 7          │
│ y1_d217_VAS ┆ 348        ┆ 1   ┆ 1.1176636e ┆ … ┆ 347     ┆ 18.670318  ┆ 143.765945 ┆ 1.1134986e │
│ _ARN        ┆            ┆     ┆ 7          ┆   ┆         ┆            ┆            ┆ 7          │
│ y1_d217_VAS ┆ 349        ┆ 1   ┆ 1.1215536e ┆ … ┆ 348     ┆ 18.78218   ┆ 143.409207 ┆ 1.1176636e │
│ _ARN        ┆            ┆     ┆ 7          ┆   ┆         ┆            ┆            ┆ 7          │
│ y1_d217_VAS ┆ 350        ┆ 1   ┆ 1.1255636e ┆ … ┆ 349     ┆ -9.416407  ┆ 137.521095 ┆ 1.1215536e │
│ _ARN        ┆            ┆     ┆ 7          ┆   ┆         ┆            ┆            ┆ 7          │
│ y1_d217_VAS ┆ 351        ┆ 1   ┆ 1.1272636e ┆ … ┆ 350     ┆ 16.402234  ┆ 153.569172 ┆ 1.1255636e │
│ _ARN        ┆            ┆     ┆ 7          ┆   ┆         ┆            ┆            ┆ 7          │
└─────────────┴────────────┴─────┴────────────┴───┴─────────┴────────────┴────────────┴────────────┘

In [556]:
player_pos_ss_df = player_pos_ss_df.with_columns(
    pl.col("play_per_game").shift(1).alias("pre_ppg"), 
    pl.col("field_x").shift(1).alias("pre_field_x"),
    pl.col("field_y").shift(1).alias("pre_field_y"),
    pl.col("timestamp").shift(1).alias("pre_timestamp")
)

player_pos_ss_df.head()

shape: (5, 10)
┌─────────────┬─────────────┬─────┬───────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ game_string ┆ play_per_ga ┆ ss  ┆ timestamp ┆ … ┆ pre_ppg ┆ pre_field_ ┆ pre_field_ ┆ pre_timest │
│ ---         ┆ me          ┆ --- ┆ ---       ┆   ┆ ---     ┆ x          ┆ y          ┆ amp        │
│ str         ┆ ---         ┆ i32 ┆ f64       ┆   ┆ i64     ┆ ---        ┆ ---        ┆ ---        │
│             ┆ i64         ┆     ┆           ┆   ┆         ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪═════════════╪═════╪═══════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ NA          ┆ null        ┆ 1   ┆ null      ┆ … ┆ null    ┆ null       ┆ null       ┆ null       │
│ y1_d061_VKA ┆ 1           ┆ 1   ┆ 63614.0   ┆ … ┆ null    ┆ -28.898772 ┆ 140.343837 ┆ null       │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 2           ┆ 1   ┆ 72964.0   ┆ … ┆ 1       ┆ -26.56044  ┆ 147.14934  ┆ 63614.0    │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 3           ┆ 1   ┆ 106614.0  ┆ … ┆ 2       ┆ -18.536207 ┆ 147.363898 ┆ 72964.0    │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
│ y1_d061_VKA ┆ 4           ┆ 1   ┆ 142414.0  ┆ … ┆ 3       ┆ 30.283269  ┆ 146.081511 ┆ 106614.0   │
│ _PHD        ┆             ┆     ┆           ┆   ┆         ┆            ┆            ┆            │
└─────────────┴─────────────┴─────┴───────────┴───┴─────────┴────────────┴────────────┴────────────┘

In [557]:
ss_2bm_pos = pl.concat([player_pos_2bm_df, player_pos_ss_df], how = "diagonal")

In [558]:
ss_2bm_pos.head()

shape: (5, 11)
┌─────────────┬─────────────┬─────┬───────────┬───┬─────────────┬─────────────┬─────────────┬──────┐
│ game_string ┆ play_per_ga ┆ 2bm ┆ timestamp ┆ … ┆ pre_field_x ┆ pre_field_y ┆ pre_timesta ┆ ss   │
│ ---         ┆ me          ┆ --- ┆ ---       ┆   ┆ ---         ┆ ---         ┆ mp          ┆ ---  │
│ str         ┆ ---         ┆ i32 ┆ f64       ┆   ┆ f64         ┆ f64         ┆ ---         ┆ i32  │
│             ┆ i64         ┆     ┆           ┆   ┆             ┆             ┆ f64         ┆      │
╞═════════════╪═════════════╪═════╪═══════════╪═══╪═════════════╪═════════════╪═════════════╪══════╡
│ NA          ┆ null        ┆ 1   ┆ null      ┆ … ┆ null        ┆ null        ┆ null        ┆ null │
│ y1_d061_VKA ┆ 1           ┆ 1   ┆ 63614.0   ┆ … ┆ 30.265505   ┆ 142.224095  ┆ null        ┆ null │
│ _PHD        ┆             ┆     ┆           ┆   ┆             ┆             ┆             ┆      │
│ y1_d061_VKA ┆ 2           ┆ 1   ┆ 72964.0   ┆ … ┆ 45.2952     ┆ 134.77536   ┆ 63614.0     ┆ null │
│ _PHD        ┆             ┆     ┆           ┆   ┆             ┆             ┆             ┆      │
│ y1_d061_VKA ┆ 3           ┆ 1   ┆ 106614.0  ┆ … ┆ 38.727397   ┆ 139.787246  ┆ 72964.0     ┆ null │
│ _PHD        ┆             ┆     ┆           ┆   ┆             ┆             ┆             ┆      │
│ y1_d061_VKA ┆ 4           ┆ 1   ┆ 142414.0  ┆ … ┆ 80.590907   ┆ 154.868247  ┆ 106614.0    ┆ null │
│ _PHD        ┆             ┆     ┆           ┆   ┆             ┆             ┆             ┆      │
└─────────────┴─────────────┴─────┴───────────┴───┴─────────────┴─────────────┴─────────────┴──────┘

In [559]:
ss_2bm_pos = ss_2bm_pos.sort(["game_string", "play_per_game"]).select(
    ["game_string", "play_per_game", "timestamp", "pre_timestamp" ,"field_x", "pre_field_x" ,"field_y", "pre_field_y"]
).drop_nulls("play_per_game")

ss_2bm_pos.head()

shape: (5, 8)
┌────────────┬────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ timestamp ┆ pre_timest ┆ field_x   ┆ pre_field ┆ field_y   ┆ pre_field │
│ g          ┆ ame        ┆ ---       ┆ amp        ┆ ---       ┆ _x        ┆ ---       ┆ _y        │
│ ---        ┆ ---        ┆ f64       ┆ ---        ┆ f64       ┆ ---       ┆ f64       ┆ ---       │
│ str        ┆ i64        ┆           ┆ f64        ┆           ┆ f64       ┆           ┆ f64       │
╞════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 1          ┆ 63614.0   ┆ null       ┆ 45.2952   ┆ 30.265505 ┆ 134.77536 ┆ 142.22409 │
│ A_PHD      ┆            ┆           ┆            ┆           ┆           ┆           ┆ 5         │
│ y1_d061_VK ┆ 1          ┆ 63614.0   ┆ null       ┆ -26.56044 ┆ -28.89877 ┆ 147.14934 ┆ 140.34383 │
│ A_PHD      ┆            ┆           ┆            ┆           ┆ 2         ┆           ┆ 7         │
│ y1_d061_VK ┆ 2          ┆ 72964.0   ┆ 63614.0    ┆ 38.727397 ┆ 45.2952   ┆ 139.78724 ┆ 134.77536 │
│ A_PHD      ┆            ┆           ┆            ┆           ┆           ┆ 6         ┆           │
│ y1_d061_VK ┆ 2          ┆ 72964.0   ┆ 63614.0    ┆ -18.53620 ┆ -26.56044 ┆ 147.36389 ┆ 147.14934 │
│ A_PHD      ┆            ┆           ┆            ┆ 7         ┆           ┆ 8         ┆           │
│ y1_d061_VK ┆ 3          ┆ 106614.0  ┆ 72964.0    ┆ 80.590907 ┆ 38.727397 ┆ 154.86824 ┆ 139.78724 │
│ A_PHD      ┆            ┆           ┆            ┆           ┆           ┆ 7         ┆ 6         │
└────────────┴────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [560]:
catcher_steals.head()

shape: (5, 5)
┌─────────────────┬───────────────┬────────────┬─────┬─────┐
│ game_string     ┆ play_per_game ┆ throw_time ┆ 2bm ┆ ss  │
│ ---             ┆ ---           ┆ ---        ┆ --- ┆ --- │
│ str             ┆ i64           ┆ f64        ┆ i32 ┆ i32 │
╞═════════════════╪═══════════════╪════════════╪═════╪═════╡
│ y1_d061_VKA_PHD ┆ 106           ┆ 2.35       ┆ 1   ┆ 0   │
│ y1_d064_VKA_PHD ┆ 177           ┆ 2.57       ┆ 0   ┆ 1   │
│ y1_d065_VAS_PHD ┆ 80            ┆ 2.41       ┆ 1   ┆ 0   │
│ y1_d070_SQF_ARN ┆ 167           ┆ 2.38       ┆ 0   ┆ 1   │
│ y1_d071_SQF_ARN ┆ 278           ┆ 2.31       ┆ 0   ┆ 1   │
└─────────────────┴───────────────┴────────────┴─────┴─────┘

In [561]:
catcher_positions = catcher_steals.join(ss_2bm_pos, on = ["game_string", "play_per_game"], how = "left").unique(["game_string", "play_per_game"]).sort(["game_string", "play_per_game"])

catcher_positions.head()

shape: (5, 11)
┌────────────┬────────────┬────────────┬─────┬───┬────────────┬────────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ throw_time ┆ 2bm ┆ … ┆ field_x    ┆ pre_field_ ┆ field_y   ┆ pre_field │
│ g          ┆ ame        ┆ ---        ┆ --- ┆   ┆ ---        ┆ x          ┆ ---       ┆ _y        │
│ ---        ┆ ---        ┆ f64        ┆ i32 ┆   ┆ f64        ┆ ---        ┆ f64       ┆ ---       │
│ str        ┆ i64        ┆            ┆     ┆   ┆            ┆ f64        ┆           ┆ f64       │
╞════════════╪════════════╪════════════╪═════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 106        ┆ 2.35       ┆ 1   ┆ … ┆ -27.213194 ┆ -30.798514 ┆ 134.60111 ┆ 122.36427 │
│ A_PHD      ┆            ┆            ┆     ┆   ┆            ┆            ┆ 5         ┆ 5         │
│ y1_d064_VK ┆ 177        ┆ 2.57       ┆ 0   ┆ … ┆ 85.860747  ┆ 88.400831  ┆ 158.75418 ┆ 156.37193 │
│ A_PHD      ┆            ┆            ┆     ┆   ┆            ┆            ┆ 4         ┆ 7         │
│ y1_d065_VA ┆ 80         ┆ 2.41       ┆ 1   ┆ … ┆ 13.233298  ┆ 14.436205  ┆ 136.51921 ┆ 138.41818 │
│ S_PHD      ┆            ┆            ┆     ┆   ┆            ┆            ┆ 5         ┆           │
│ y1_d070_SQ ┆ 167        ┆ 2.38       ┆ 0   ┆ … ┆ 36.834054  ┆ 19.612112  ┆ 135.08591 ┆ 149.62291 │
│ F_ARN      ┆            ┆            ┆     ┆   ┆            ┆            ┆ 3         ┆ 7         │
│ y1_d071_SQ ┆ 278        ┆ 2.31       ┆ 0   ┆ … ┆ 29.055503  ┆ 35.106922  ┆ 137.46061 ┆ 135.18895 │
│ F_ARN      ┆            ┆            ┆     ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴────────────┴─────┴───┴────────────┴────────────┴───────────┴───────────┘

In [562]:
final_steal_df.head()

shape: (5, 27)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ at_bat ┆ 2bm_field ┆ … ┆ pre_2bm_f ┆ pre_2bm_f ┆ pre_2bm_t ┆ steal_suc │
│ g          ┆ ame        ┆ ---    ┆ _x        ┆   ┆ ield_x    ┆ ield_y    ┆ imestamp  ┆ cessful   │
│ ---        ┆ ---        ┆ i64    ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i64        ┆        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ i32       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 106        ┆ 33     ┆ 14.220055 ┆ … ┆ 28.918463 ┆ 134.45314 ┆ 3.335664e ┆ 0         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 8         ┆ 6         ┆           │
│ y1_d061_VK ┆ 213        ┆ 59     ┆ -8.948758 ┆ … ┆ -14.77433 ┆ 149.26437 ┆ 7.036714e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆ 3         ┆ 5         ┆ 6         ┆           │
│ y1_d062_VK ┆ 230        ┆ 53     ┆ 55.694929 ┆ … ┆ 61.461092 ┆ 121.55183 ┆ 7.006084e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 8         ┆ 6         ┆           │
│ y1_d063_VK ┆ 200        ┆ 56     ┆ 20.057146 ┆ … ┆ 19.59941  ┆ 145.59229 ┆ 6.579765e ┆ 0         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 6         ┆           │
│ y1_d063_VK ┆ 253        ┆ 67     ┆ 30.047615 ┆ … ┆ 39.165271 ┆ 147.66826 ┆ 8.199265e ┆ 1         │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 3         ┆ 6         ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [563]:
new_df = final_steal_df.join(catcher_positions, on = ["game_string", "play_per_game"], how = "left").with_columns(
    pl.col("field_x").fill_null(pl.col("2bm_field_x")),
    pl.col("field_y").fill_null(pl.col("2bm_field_y")),
    pl.col("pre_field_x").fill_null(pl.col("pre_2bm_field_x")),
    pl.col("pre_field_y").fill_null(pl.col("pre_2bm_field_y")),
    pl.col("timestamp").fill_null(pl.col("2bm_timestamp")),
    pl.col("pre_timestamp").fill_null(pl.col("pre_2bm_timestamp")),
    pl.col("2bm").fill_null(0),
    pl.col("ss").fill_null(0)
).sort(["game_string", "play_per_game"])

print(new_df.shape)
new_df.head()

(654, 36)

shape: (5, 36)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ at_bat ┆ 2bm_field ┆ … ┆ field_x   ┆ pre_field ┆ field_y   ┆ pre_field │
│ g          ┆ ame        ┆ ---    ┆ _x        ┆   ┆ ---       ┆ _x        ┆ ---       ┆ _y        │
│ ---        ┆ ---        ┆ i64    ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---       │
│ str        ┆ i64        ┆        ┆ f64       ┆   ┆           ┆ f64       ┆           ┆ f64       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 106        ┆ 33     ┆ 14.220055 ┆ … ┆ -27.21319 ┆ -30.79851 ┆ 134.60111 ┆ 122.36427 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆ 4         ┆ 4         ┆ 5         ┆ 5         │
│ y1_d061_VK ┆ 213        ┆ 59     ┆ -8.948758 ┆ … ┆ -8.948758 ┆ -14.77433 ┆ 140.72619 ┆ 149.26437 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 3         ┆ 4         ┆ 5         │
│ y1_d062_VK ┆ 230        ┆ 53     ┆ 55.694929 ┆ … ┆ 55.694929 ┆ 61.461092 ┆ 120.08158 ┆ 121.55183 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆ 8         │
│ y1_d063_VK ┆ 200        ┆ 56     ┆ 20.057146 ┆ … ┆ 20.057146 ┆ 19.59941  ┆ 145.63579 ┆ 145.59229 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 9         ┆           │
│ y1_d063_VK ┆ 253        ┆ 67     ┆ 30.047615 ┆ … ┆ 30.047615 ┆ 39.165271 ┆ 142.70907 ┆ 147.66826 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 2         ┆ 3         │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [582]:
new_df_nulls = new_df.filter(~
    (pl.col("steal_successful") == 0) &
    (pl.col("throw_time").is_null())
)

print(new_df_nulls.shape)
new_df_nulls.head()

(393, 36)

shape: (5, 36)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ game_strin ┆ play_per_g ┆ at_bat ┆ 2bm_field ┆ … ┆ field_x   ┆ pre_field ┆ field_y   ┆ pre_field │
│ g          ┆ ame        ┆ ---    ┆ _x        ┆   ┆ ---       ┆ _x        ┆ ---       ┆ _y        │
│ ---        ┆ ---        ┆ i64    ┆ ---       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---       │
│ str        ┆ i64        ┆        ┆ f64       ┆   ┆           ┆ f64       ┆           ┆ f64       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ y1_d061_VK ┆ 213        ┆ 59     ┆ -8.948758 ┆ … ┆ -8.948758 ┆ -14.77433 ┆ 140.72619 ┆ 149.26437 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆ 3         ┆ 4         ┆ 5         │
│ y1_d062_VK ┆ 230        ┆ 53     ┆ 55.694929 ┆ … ┆ 55.694929 ┆ 61.461092 ┆ 120.08158 ┆ 121.55183 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆ 8         │
│ y1_d063_VK ┆ 253        ┆ 67     ┆ 30.047615 ┆ … ┆ 30.047615 ┆ 39.165271 ┆ 142.70907 ┆ 147.66826 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 2         ┆ 3         │
│ y1_d064_VK ┆ 80         ┆ 19     ┆ 17.550415 ┆ … ┆ 17.550415 ┆ 24.392722 ┆ 138.99968 ┆ 146.35625 │
│ A_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 1         ┆           │
│ y1_d066_VA ┆ 27         ┆ 8      ┆ 66.71844  ┆ … ┆ 66.71844  ┆ 46.671559 ┆ 122.78962 ┆ 130.90292 │
│ S_PHD      ┆            ┆        ┆           ┆   ┆           ┆           ┆ 5         ┆ 2         │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [589]:
X = new_df_nulls.drop("steal_successful")
y = new_df_nulls["steal_successful"]

print(x.shape)
print(y.shape)

X = X.to_pandas()
y = y.to_pandas()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, train_size = .8, random_state = 42, stratify = y)

(393, 35)
(393,)

field_x = catcher_positions["field_x"].head(5)
field_y = catcher_positions["field_y"].head(5)
pre_x = catcher_positions["pre_field_x"].head(5)
pre_y = catcher_positions["pre_field_y"].head(5)
home_x = 0
home_y = 0
base_1x = 45 * np.sqrt(2)
base_1y = 45 * np.sqrt(2)
base_2x = 0
base_2y = 127.279221
base_3x = -45 * np.sqrt(2)
base_3y = 45 * np.sqrt(2)

plt.scatter(home_x, home_y, color = "white", edgecolor = "black")
plt.scatter(base_1x, base_1y, color = "white", edgecolor = "black")
plt.scatter(base_2x, base_2y, color = "white", edgecolor = "black")
plt.scatter(base_3x, base_3y, color = "white", edgecolor = "black")
plt.scatter(field_x, field_y, color = "blue")
plt.scatter(pre_x, pre_y, color = "green")
plt.xlim([-80, 100])
plt.ylim([-80, 150])

In [ ]:
dcov_df = final_steal_df.with_columns(
    # FInd the change in x, y, and time
    change_x_1b = (pl.col("next_2b_x") - pl.col("1b_field_x")).over(["game_string", "play_per_game"]),
    change_y_1b = (pl.col("next_2b_y") - pl.col("1b_field_y")).over(["game_string", "play_per_game"]),
    change_time = (pl.col("next_2b_time") - pl.col("1b_timestamp")).over(["game_string", "play_per_game"])
).with_columns(
    # convert change_time to seconds and calculate distance of step
    change_time_sec = pl.col("change_time") / 1000,
    dcov_step = (pl.col("change_x_1b") ** 2 + pl.col("change_y_1b") ** 2).sqrt().over(["game_string", "play_per_game"])
).with_columns(
    dcov_total = pl.col("dcov_step").sum().over(["game_string", "play_per_game"]),
    dcov_running = pl.col("dcov_step").cum_sum().over(["game_string", "play_per_game"])
).with_columns(
    # calculate instantaneous velo, accel, and jerk
    i_vel = pl.col("dcov_step") / pl.col("change_time_sec"),
    i_accel = (pl.col("dcov_step") / (pl.col("change_time_sec")) ** 2),
    i_jerk = (pl.col("dcov_step") / (pl.col("change_time_sec")) ** 3)
).select(
        ["game_string", "play_per_game", "at_bat", "2bm_field_x", "2bm_field_y", "1b_field_x", "1b_field_y", "next_2b_x", "next_2b_y", "change_time_sec",
         "dcov_step", "dcov_total", "dcov_running", "i_vel", "i_accel", "i_jerk", "steal_successful"]
)

In [266]:
dcov_df.head()

shape: (5, 16)
┌─────────────┬────────────┬────────┬────────────┬───┬────────────┬──────────┬──────────┬──────────┐
│ game_string ┆ play_per_g ┆ at_bat ┆ 2bm_field_ ┆ … ┆ dcov_runni ┆ i_vel    ┆ i_accel  ┆ i_jerk   │
│ ---         ┆ ame        ┆ ---    ┆ x          ┆   ┆ ng         ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ ---        ┆ i64    ┆ ---        ┆   ┆ ---        ┆ f64      ┆ f64      ┆ f64      │
│             ┆ i64        ┆        ┆ f64        ┆   ┆ f64        ┆          ┆          ┆          │
╞═════════════╪════════════╪════════╪════════════╪═══╪════════════╪══════════╪══════════╪══════════╡
│ y1_d061_VKA ┆ 106        ┆ 33     ┆ 14.220055  ┆ … ┆ null       ┆ null     ┆ null     ┆ null     │
│ _PHD        ┆            ┆        ┆            ┆   ┆            ┆          ┆          ┆          │
│ y1_d061_VKA ┆ 213        ┆ 59     ┆ -8.948758  ┆ … ┆ 74.737633  ┆ 0.754926 ┆ 0.007626 ┆ 0.000077 │
│ _PHD        ┆            ┆        ┆            ┆   ┆            ┆          ┆          ┆          │
│ y1_d062_VKA ┆ 230        ┆ 53     ┆ 55.694929  ┆ … ┆ 61.74143   ┆ 1.703212 ┆ 0.046985 ┆ 0.001296 │
│ _PHD        ┆            ┆        ┆            ┆   ┆            ┆          ┆          ┆          │
│ y1_d063_VKA ┆ 200        ┆ 56     ┆ 20.057146  ┆ … ┆ null       ┆ null     ┆ null     ┆ null     │
│ _PHD        ┆            ┆        ┆            ┆   ┆            ┆          ┆          ┆          │
│ y1_d063_VKA ┆ 253        ┆ 67     ┆ 30.047615  ┆ … ┆ 62.789566  ┆ 1.885573 ┆ 0.056624 ┆ 0.0017   │
│ _PHD        ┆            ┆        ┆            ┆   ┆            ┆          ┆          ┆          │
└─────────────┴────────────┴────────┴────────────┴───┴────────────┴──────────┴──────────┴──────────┘

game_filter = player_positions_df.filter(
    (pl.col("game_string") == "y1_d061_VKA_PHD"),
    (pl.col("play_per_game").is_in([213, 214]))
    )

game_filter